pr: favorites, add to the favorite list
partizanen69/team-project-foodies-backend pull request #14
Opened 2024-06-06 23:44 UTC by OstafiichukO

2024-06-07 06:22 UTC, partizanen69 requested changes

2024-06-07 06:22 UTC, partizanen69 commented on services/favoriteServices.js
> +  }
Ця валідація має бути в контроллері або в роутері в якості middleware

2024-06-07 06:22 UTC, partizanen69 commented on services/favoriteServices.js
> +  if (!Types.ObjectId.isValid(user)) {
Оце або в контроллері, або взагаіл не треба, оскільки user тягнеться з бази

2024-06-07 06:22 UTC, partizanen69 commented on db/favorite.model.js
> +  },
Схема погана. Запити по такій колекції будуть дуже важкими. Тут взагалі є два варіанти:
- або favorites додавай в юзера
- або роби цю схему пласкою { userId, recipeId } (звязка цих двох полів має бути унікальною)

2024-06-07 06:22 UTC, partizanen69 commented on services/favoriteServices.js
> +    return resp ? resp : null;
Занадто складна логіка для цього кейса через те що схема не оптимальна

2024-06-07 08:33 UTC, OstafiichukO commented
Перевірте будь ласка чи правильно передаються ID юзера і рецепта та чи middleware ок

2024-06-07 11:27 UTC, partizanen69 commented
пофікси конфлікти

2024-06-07 11:31 UTC, partizanen69 requested changes

2024-06-07 11:31 UTC, partizanen69 commented on schemas/recipeSchemas.js
> +  id: Joi.string().required().pattern(/^[0-9a-fA-F]{24}$/).messages({
у mongoose є вбудована функція для цього https://stackoverflow.com/questions/13850819/can-i-determine-if-a-string-is-a-mongodb-objectid

2024-06-07 11:31 UTC, partizanen69 commented on services/recipesServices.js
> +export const addFavoriteRecipe = async (userId, recipeId) => {
Можна простіше оновлення робити UserModel.updateOne({ id }, {$push: { favorites: ObjectId(recipeId) }))
Якщо хочеш зміни, все одно конфлікти будеш фіксити

2024-06-07 13:31 UTC, OstafiichukO commented on services/recipesServices.js
> +export const addFavoriteRecipe = async (userId, recipeId) => {
звідки береться `ObjectId`, з mongoose?

2024-06-07 16:23 UTC, partizanen69 commented on services/recipesServices.js
> +export const addFavoriteRecipe = async (userId, recipeId) => {
так

2024-06-08 08:11 UTC, partizanen69 approved these changes

2024-06-08 08:11 UTC, partizanen69 commented on helpers/middlewares/validate.middleware.js
> +export const valdateAddFavoriteRecipe = () => {
Взагалі тут не обовязково повертати фуенкцію з функції. Це може бути просто функція.

2024-06-08 08:11 UTC, partizanen69 commented on routes/recipesRouter.js
> +  validateIncomingPayload(addFavoriteRecipeSchema, ValidateProp.body),
ValidateProp.body там за замовчуванням. Можна не передавати.

2024-06-08 08:11 UTC, partizanen69 commented on schemas/recipeSchemas.js
> +export const addFavoriteRecipeSchema = Joi.object({
В тебе id передається в   params а  ти його валідуєш в боді.

2024-06-08 08:12 UTC, merged